# NumPy Student Workbook

Questions only. Write answers in the empty code cells below each question.

Q1. Create a NumPy array containing 10, 20, 30, 40, 50.

In [ ]:
import numpy as np

array1 = np.array([10, 20, 30, 40, 50])
print(array1)

[10 20 30 40 50]


Q2. Create numbers from 1 to 20.

In [ ]:
import numpy as np

numbers_1_to_20 = np.arange(1, 21)
print(numbers_1_to_20)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Q3. Create even numbers from 2 to 20.

In [ ]:
import numpy as np

even_numbers = np.arange(2, 21, 2)
print(even_numbers)

[ 2  4  6  8 10 12 14 16 18 20]


Q4. Create a 3×4 matrix of zeros.

In [ ]:
import numpy as np

zeros_matrix = np.zeros((3, 4))
print(zeros_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Q5. Create a 4×3 matrix of ones.

In [ ]:
import numpy as np

ones_matrix = np.ones((4, 3))
print(ones_matrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Q6. Generate 10 evenly spaced values between 0 and 1.

In [ ]:
import numpy as np

evenly_spaced_values = np.linspace(0, 1, 10)
print(evenly_spaced_values)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Q7. Create a 2×3 array and find shape, ndim and dtype.

In [ ]:
import numpy as np

array_2x3 = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", array_2x3)
print("Shape:", array_2x3.shape)
print("Number of dimensions (ndim):", array_2x3.ndim)
print("Data type (dtype):", array_2x3.dtype)

Q8. Create a 4×5 array and find shape, size and ndim.

In [ ]:
import numpy as np

array_4x5 = np.arange(20).reshape(4, 5) # Create 20 numbers and reshape into 4x5
print("Array:\n", array_4x5)
print("Shape:", array_4x5.shape)
print("Size (total elements):", array_4x5.size)
print("Number of dimensions (ndim):", array_4x5.ndim)

Array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Shape: (4, 5)
Size (total elements): 20
Number of dimensions (ndim): 2


Q9. Convert [1,2,3,4,5] to float datatype.

In [ ]:
import numpy as np

int_array = np.array([1, 2, 3, 4, 5])
float_array = int_array.astype(float)
print("Original array:", int_array)
print("Converted to float:", float_array)
print("Datatype of float array:", float_array.dtype)

Q10. Create numbers 1–12 and reshape into 3×4, 2×6 and 4×3.

In [ ]:
import numpy as np

numbers_1_to_12 = np.arange(1, 13)
print("Original numbers (1-12):", numbers_1_to_12)

matrix_3x4 = numbers_1_to_12.reshape(3, 4)
print("\nReshaped to 3x4 matrix:\n", matrix_3x4)

matrix_2x6 = numbers_1_to_12.reshape(2, 6)
print("\nReshaped to 2x6 matrix:\n", matrix_2x6)

matrix_4x3 = numbers_1_to_12.reshape(4, 3)
print("\nReshaped to 4x3 matrix:\n", matrix_4x3)

Original numbers (1-12): [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to 3x4 matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped to 2x6 matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Reshaped to 4x3 matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Q11. Create np.arange(20) and reshape into 4×5 and 5×4.

In [ ]:
import numpy as np

# Create an array with values 0 through 19
arr = np.arange(20)

# Reshape into 4×5
arr_4x5 = arr.reshape(4, 5)

# Reshape into 5×4
arr_5x4 = arr.reshape(5, 4)

print("Original:")
print(arr)

print("\n4×5:")
print(arr_4x5)

print("\n5×4:")
print(arr_5x4)

**Q12**. Explain why np.arange(10).reshape(3,4) produces an error.

The error in `np.arange(10).reshape(3,4)` occurs because `np.arange(10)` creates an array with 10 elements (0 to 9). When you try to reshape it into a 3x4 matrix, NumPy expects 3 * 4 = 12 elements. Since the number of elements in the original array (10) does not match the number of elements required for the new shape (12), a `ValueError` is raised.

In [ ]:
import numpy as np

# This will produce an error
try:
    error_array = np.arange(10).reshape(3, 4)
    print(error_array)
except ValueError as e:
    print(f"Error: {e}")

Error: cannot reshape array of size 10 into shape (3,4)


To correctly reshape an array with 10 elements, the product of the new dimensions must equal 10. For example, a 2x5 or 5x2 matrix would work:

In [ ]:
import numpy as np

correct_array = np.arange(10)

# Correctly reshape to 2x5
reshaped_2x5 = correct_array.reshape(2, 5)
print("Reshaped to 2x5:\n", reshaped_2x5)

# Correctly reshape to 5x2
reshaped_5x2 = correct_array.reshape(5, 2)
print("\nReshaped to 5x2:\n", reshaped_5x2)

Reshaped to 2x5:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Q13. Using a 4×4 array, extract the first element.

In [ ]:
import numpy as np

# Create a 4x4 array (e.g., using arange and reshape)
array_4x4 = np.arange(1, 17).reshape(4, 4)
print("Original 4x4 array:\n", array_4x4)

# Extract the first element (top-left)
first_element = array_4x4[0, 0]
print("\nFirst element:", first_element)

Original 4x4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

First element: 1


Q14. Extract the value 10 from a 4×4 array created using arange.

In [ ]:
import numpy as np

# Create a 4x4 array using arange
array_4x4 = np.arange(1, 17).reshape(4, 4)
print("Original 4x4 array:\n", array_4x4)

# Extract the value 10
# We know 10 is at row 2, column 1 (0-indexed)
value_10 = array_4x4[2, 1]
print("\nExtracted value 10:", value_10)

Original 4x4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Extracted value 10: 10


Q15. Extract the last element.

In [ ]:
import numpy as np

# Assuming array_4x4 from previous questions is available, or create it if not
# (Using the one defined in Q14 to be consistent)
array_4x4 = np.arange(1, 17).reshape(4, 4)
print("Original 4x4 array:\n", array_4x4)

# Extract the last element
last_element = array_4x4[-1, -1] # or array_4x4[3, 3] for a 4x4 array
print("\nLast element:", last_element)

Original 4x4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Last element: 16


In [ ]:
import numpy as np

# Assuming array_4x4 is available from previous questions
# If not, create it:
array_4x4 = np.arange(1, 17).reshape(4, 4)
print("Original 4x4 array:\n", array_4x4)

# Extract the first row
first_row = array_4x4[0, :]
print("\nFirst row:", first_row)

Original 4x4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

First row: [1 2 3 4]


Q16. Extract the first row.

In [ ]:
import numpy as np

# Assuming array_4x4 is available from previous questions
# If not, create it:
array_4x4 = np.arange(1, 17).reshape(4, 4)
print("Original 4x4 array:\n", array_4x4)

# Extract the third row (index 2 for 0-based indexing)
third_row = array_4x4[2, :]
print("\nThird row:", third_row)

Original 4x4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Third row: [ 9 10 11 12]


Q17. Extract the third row.

In [ ]:
import numpy as np

# Assuming array_4x4 is available from previous questions
# If not, create it:
array_4x4 = np.arange(1, 17).reshape(4, 4)
print("Original 4x4 array:\n", array_4x4)

# Extract the second column (index 1 for 0-based indexing)
second_column = array_4x4[:, 1]
print("\nSecond column:", second_column)

Original 4x4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Second column: [ 2  6 10 14]


Q18. Extract the second column.

In [ ]:
import numpy as np

# Assuming array_4x4 is available from previous questions
# If not, create it:
array_4x4 = np.arange(1, 17).reshape(4, 4)
print("Original 4x4 array:\n", array_4x4)

# Extract the last column
last_column = array_4x4[:, -1]
print("\nLast column:", last_column)

Original 4x4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Last column: [ 4  8 12 16]


Q19. Extract the last column.

In [ ]:
import numpy as np

arr = np.arange(20).reshape(4, 5)

last_column = arr[:, -1]

print(last_column)

In [ ]:
import numpy as np

arr = np.arange(20).reshape(4, 5)

alternate_rows = arr[::2, :]

print(alternate_rows)

[[ 0  1  2  3  4]
 [10 11 12 13 14]]


Q20. Extract first two rows.

In [ ]:
import numpy as np

arr = np.arange(20).reshape(4, 5)

first_two_rows = arr[:2]

print(first_two_rows)

Q21. Extract last two rows.

In [ ]:
import numpy as np

arr = np.arange(20).reshape(4, 5)

last_two_rows = arr[-2:]

print(last_two_rows)

Q22. Extract first three columns.

In [ ]:
import numpy as np

arr = np.arange(20).reshape(4, 5)

first_three_columns = arr[:, :3]

print(first_three_columns)

Q23. Extract last two columns.

In [ ]:
import numpy as np

arr = np.arange(20).reshape(4, 5)

last_two_columns = arr[:, -2:]

print(last_two_columns)

Q24. Extract a 2×2 center block.

In [ ]:
import numpy as np

arr = np.arange(20).reshape(4, 5)

center_block = arr[1:3, 1:3]

print(center_block)

Q25. Extract bottom-right 3×3 block.

In [ ]:
import numpy as np

arr = np.arange(20).reshape(4, 5)

bottom_right = arr[-3:, -3:]

print(bottom_right)

Q26. Extract center element.

In [ ]:
import numpy as np

arr = np.arange(20).reshape(4, 5)

center_elements = arr[1:3, 2]

print(center_elements)

Q27. Extract center 3×3 block.

In [ ]:
import numpy as np

arr = np.arange(20).reshape(4, 5)

center_block = arr[1:4, 1:4]

print(center_block)

Q28. Extract top-right corner block.

In [ ]:
import numpy as np

arr = np.arange(20).reshape(4, 5)

top_right = arr[:2, -2:]

print(top_right)

Q29. Extract bottom-left corner block.

In [ ]:
import numpy as np

arr = np.arange(20).reshape(4, 5)

bottom_left = arr[-2:, :2]

print(bottom_left)

Q30. Extract the main diagonal manually using slicing/indexing.

In [ ]:
import numpy as np

arr = np.arange(20).reshape(4, 5)

main_diagonal = [arr[0,0], arr[1,1], arr[2,2], arr[3,3]]

print(main_diagonal)

Q31. Extract every alternate row.

In [ ]:
import numpy as np

arr = np.arange(20).reshape(4, 5)

alternate_rows = arr[::2]

print(alternate_rows)

Q32. Extract every alternate column.

In [ ]:
import numpy as np

arr = np.arange(20).reshape(4, 5)

alternate_columns = arr[:, ::2]

print(alternate_columns)

[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]]


Q33. Reverse the rows.

Q34. Reverse the columns.

In [ ]:
import numpy as np

arr = np.arange(20).reshape(4, 5)

reversed_columns = arr[:, ::-1]

print(reversed_columns)

[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]


Q35. Reverse the entire matrix.

In [ ]:
import numpy as np

arr = np.arange(20).reshape(4, 5)

reversed_matrix = arr[::-1, ::-1]

print(reversed_matrix)

[[19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


Q36. Extract a 3×3 reversed center block.

In [ ]:
import numpy as np

arr = np.arange(20).reshape(4, 5)

# Extract the 3x3 center block first, then reverse it
center_block = arr[0:3, 1:4] # Adjusting indices for a 3x3 block in a 4x5 array
reversed_center_block = center_block[::-1, ::-1]

print(reversed_center_block)

[[13 12 11]
 [ 8  7  6]
 [ 3  2  1]]


Q37. Extract only the corner elements.

In [ ]:
import numpy as np

arr = np.arange(20).reshape(4, 5)

# Extract corner elements
corner_elements = np.array([arr[0, 0], arr[0, -1], arr[-1, 0], arr[-1, -1]])

print(corner_elements)

[ 0  4 15 19]


Q38. Extract only the border elements.

In [ ]:
import numpy as np

arr = np.arange(20).reshape(4, 5)

# Extract border elements
first_row = arr[0, :]
last_row = arr[-1, :]
# Extract first column excluding corners
first_column_middle = arr[1:-1, 0]
# Extract last column excluding corners
last_column_middle = arr[1:-1, -1]

border_elements = np.concatenate((first_row, last_row, first_column_middle, last_column_middle))

print(border_elements)

[ 0  1  2  3  4 15 16 17 18 19  5 10  9 14]


Q39. Increase sales [100,200,300,400] by 10.

In [ ]:
import numpy as np

sales = np.array([100, 200, 300, 400])
increased_sales = sales + 10

print("Original sales:", sales)
print("Increased sales:", increased_sales)

Original sales: [100 200 300 400]
Increased sales: [110 210 310 410]


Q40. Increase salaries by 15%.

In [ ]:
import numpy as np

salaries = np.array([50000, 60000, 75000, 45000])
increased_salaries = salaries * 1.15

print("Original salaries:", salaries)
print("Increased salaries (by 15%):", increased_salaries)

Original salaries: [50000 60000 75000 45000]
Increased salaries (by 15%): [57500. 69000. 86250. 51750.]


Q41. Apply 18% GST to prices.

In [ ]:
import numpy as np

prices = np.array([100, 250, 500, 120])
gst_factor = 1.18 # 100% (original price) + 18% (GST)

prices_with_gst = prices * gst_factor

print("Original prices:", prices)
print("Prices with 18% GST:", prices_with_gst)

Original prices: [100 250 500 120]
Prices with 18% GST: [118.  295.  590.  141.6]


Q42. Subtract 5 from every element.

In [ ]:
import numpy as np

original_array = np.array([10, 20, 30, 40, 50])
subtracted_array = original_array - 5

print("Original array:", original_array)
print("Array after subtracting 5:", subtracted_array)

Original array: [10 20 30 40 50]
Array after subtracting 5: [ 5 15 25 35 45]


Q43. Find total sales.

In [ ]:
import numpy as np

# Assuming 'sales' array is available from Q39
# sales = np.array([100, 200, 300, 400])

total_sales = np.sum(sales)

print("Original sales array:", sales)
print("Total sales:", total_sales)

Original sales array: [100 200 300 400]
Total sales: 1000


Q44. Find average sales.

In [ ]:
import numpy as np

# Assuming 'sales' array is available from Q39
# sales = np.array([100, 200, 300, 400])

average_sales = np.mean(sales)

print("Original sales array:", sales)
print("Average sales:", average_sales)

Original sales array: [100 200 300 400]
Average sales: 250.0


Q45. Find maximum sales.

In [ ]:
import numpy as np

# Assuming 'sales' array is available from Q39
# sales = np.array([100, 200, 300, 400])

maximum_sales = np.max(sales)

print("Original sales array:", sales)
print("Maximum sales:", maximum_sales)

Original sales array: [100 200 300 400]
Maximum sales: 400


Q46. Find minimum sales.

In [ ]:
import numpy as np

# Assuming 'sales' array is available from Q39
# sales = np.array([100, 200, 300, 400])

minimum_sales = np.min(sales)

print("Original sales array:", sales)
print("Minimum sales:", minimum_sales)

Original sales array: [100 200 300 400]
Minimum sales: 100


Q47. Find standard deviation.

In [ ]:
import numpy as np

# Assuming 'sales' array is available from Q39
# sales = np.array([100, 200, 300, 400])

standard_deviation_sales = np.std(sales)

print("Original sales array:", sales)
print("Standard deviation of sales:", standard_deviation_sales)

Original sales array: [100 200 300 400]
Standard deviation of sales: 111.80339887498948


Q48. Find variance.

In [ ]:
import numpy as np

# Assuming 'sales' array is available from Q39
# sales = np.array([100, 200, 300, 400])

variance_sales = np.var(sales)

print("Original sales array:", sales)
print("Variance of sales:", variance_sales)

Original sales array: [100 200 300 400]
Variance of sales: 12500.0


Q49. Find median.

In [ ]:
import numpy as np

# Assuming 'sales' array is available from Q39
# sales = np.array([100, 200, 300, 400])

median_sales = np.median(sales)

print("Original sales array:", sales)
print("Median sales:", median_sales)

Original sales array: [100 200 300 400]
Median sales: 250.0


Q50. Mini Project: Analyze a sales dataset using NumPy.

In [ ]:
import numpy as np

np.random.seed(42)

data = np.column_stack([
    np.arange(1001, 2001),                  # Order_ID
    np.random.randint(1, 101, 1000),        # Product_ID
    np.random.randint(1, 20, 1000),         # Quantity
    np.random.randint(100, 5000, 1000),     # Unit_Price
    np.random.randint(0, 31, 1000),         # Discount
    np.random.randint(500, 50000, 1000),    # Sales
    np.random.randint(100, 15000, 1000),    # Profit
    np.random.randint(1, 6, 1000),          # Region_ID
    np.random.randint(10000, 20000, 1000),  # Customer_ID
    np.random.randint(1, 6, 1000)           # Rating
])

data.shape

(1000, 10)

In [ ]:
data

array([[ 1001,    52,     2, ...,     2, 18737,     2],
       [ 1002,    93,    15, ...,     4, 12728,     2],
       [ 1003,    15,     8, ...,     1, 16726,     2],
       ...,
       [ 1998,    18,    11, ...,     3, 18505,     4],
       [ 1999,   100,     1, ...,     3, 10564,     1],
       [ 2000,    86,     7, ...,     5, 19793,     3]])

Q1. Dataset Exploration

Find:

Shape
Number of Dimensions
Datatype
Total Number of Elements

Q2. First Look at Data

Display:

First 10 rows

Last 10 rows

Q3. Using the Sales column:(Sales Column number 5)

Find:

Total Sales

Average Sales

Maximum Sales

Minimum Sales

Q4. Using the Profit column:(column number 6)

Find:

Total Profit

Average Profit

Maximum Profit

Q5. Indexing Challenge

Display:

Row 100

Row 500

Row 999

Q6. Slicing Challenge

Display:

Rows 100–200

First 5 columns

Last 3 columns

Q7. Advanced Slicing

Display:

Every alternate row

Every alternate column

Dataset in reverse order

Q8. Broadcasting

Management decides to increase all sales by 10%.

Create a new sales array with updated values.

Q9. Business Filtering

Find:

Number of orders where Sales > ₹25,000

Number of orders where Profit > ₹5,000

Q10. Management Report

Create a final report showing:

Total Sales

Average Sales

Total Profit

Average Profit

Highest Sale

Highest Profit

Number of High-Value Orders (Sales > ₹25,000)